services:
  nginx:
    image: nginx:1.13.7
    container_name: nginx-sissa
    depends_on:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    ports:
      - 8080:80
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask:0.0.1
    container_name: flask-sissa
    volumes:
      - ./code/:/code/
      - ./uploads/:/uploads/ # Volumen para almacenamiento de archivos
    environment:
      - FLASK_APP=/code/main.py
      - SECRET_KEY=clave_encriptada_de_prueba
      # Variables para Flask-Limiter
      - RATELIMIT_HEADERS_ENABLED=true # Agrega headers para indicar estado de límite
      # Variables de conexión a la base de datos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sissa_postgres_db
    command: flask run --host=0.0.0.0
    networks:
      my-network:
        aliases:
          - flask-app
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: sissa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sissa_postgres_db
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network
    ports:
      - 5432:5432

networks:
  my-network:
