export const programasDummy = [
  {
    id: 1,
    dependencia: "Secretaría de Educación",
    domicilio: "Av. de la Educación 123",
    telefono: "555-1234",
    nombreTitular: "Juan Pérez",
    cargoTitular: "Director",
    departamento: "Educación Primaria",
    nombreJefe: "María López",
    nombreResponsable: "Carlos García",
    puestoResponsable: "Coordinador",
    correoResponsable: "carlos.garcia@educacion.gob",
    nombrePrograma: "Programa de Tutoría",
    objetivo: "Mejorar el rendimiento escolar",
    actividades: "Clases de apoyo, tutorías personalizadas",
    carreras: "Pedagogía, Psicología",
    minAlumnos: 10,
    maxAlumnos: 30,
  },
  {
    id: 2,
    dependencia: "Secretaría de Salud",
    domicilio: "Av. de la Salud 456",
    telefono: "555-5678",
    nombreTitular: "Ana Torres",
    cargoTitular: "Gerente",
    departamento: "Salud Pública",
    nombreJefe: "Luis Martínez",
    nombreResponsable: "Sofía Ramírez",
    puestoResponsable: "Asistente",
    correoResponsable: "sofia.ramirez@salud.gob",
    nombrePrograma: "Campaña de Vacunación",
    objetivo: "Aumentar la cobertura de vacunación",
    actividades: "Charlas informativas, jornadas de vacunación",
    carreras: "Medicina, Enfermería",
    minAlumnos: 5,
    maxAlumnos: 20,
  },
  {
    id: 3,
    dependencia: "Secretaría de Cultura",
    domicilio: "Calle de las Artes 789",
    telefono: "555-9876",
    nombreTitular: "Pedro Sánchez",
    cargoTitular: "Cultural",
    departamento: "Promoción Cultural",
    nombreJefe: "Elena Gómez",
    nombreResponsable: "Fernando Díaz",
    puestoResponsable: "Gestor Cultural",
    correoResponsable: "fernando.diaz@cultura.gob",
    nombrePrograma: "Taller de Artes Plásticas",
    objetivo: "Fomentar la creatividad artística",
    actividades: "Clases de pintura, escultura",
    carreras: "Arte, Diseño",
    minAlumnos: 8,
    maxAlumnos: 25,
  },
  {
    id: 4,
    dependencia: "Secretaría de Medio Ambiente",
    domicilio: "Av. Ecológica 101",
    telefono: "555-6543",
    nombreTitular: "Laura Martínez",
    cargoTitular: "Directora",
    departamento: "Conservación",
    nombreJefe: "Javier Torres",
    nombreResponsable: "Claudia Ruiz",
    puestoResponsable: "Ecóloga",
    correoResponsable: "claudia.ruiz@medioambiente.gob",
    nombrePrograma: "Programa de Reforestación",
    objetivo: "Reforestar áreas degradadas",
    actividades: "Plantación de árboles, talleres de educación ambiental",
    carreras: "Biología, Ecología",
    minAlumnos: 15,
    maxAlumnos: 40,
  },
  {
    id: 5,
    dependencia: "Secretaría de Deporte",
    domicilio: "Calle del Deporte 202",
    telefono: "555-3210",
    nombreTitular: "Roberto Gómez",
    cargoTitular: "Director",
    departamento: "Promoción Deportiva",
    nombreJefe: "Patricia López",
    nombreResponsable: "Diego Fernández",
    puestoResponsable: "Entrenador",
    correoResponsable: "diego.fernandez@deporte.gob",
    nombrePrograma: "Escuelas de Deporte",
    objetivo: "Fomentar la actividad física en jóvenes",
    actividades: "Entrenamientos, torneos deportivos",
    carreras: "Educación Física, Deportes",
    minAlumnos: 12,
    maxAlumnos: 35,
  },
  {
    id: 6,
    dependencia: "Secretaría de Desarrollo Social",
    domicilio: "Calle del Progreso 303",
    telefono: "555-7890",
    nombreTitular: "María Ruiz",
    cargoTitular: "Coordinadora",
    departamento: "Inclusión Social",
    nombreJefe: "Fernando Pérez",
    nombreResponsable: "Ana Torres",
    puestoResponsable: "Asistente Social",
    correoResponsable: "ana.torres@desarroll osocial.gob",
    nombrePrograma: "Programa de Capacitación Laboral",
    objetivo: "Mejorar la empleabilidad de jóvenes",
    actividades: "Talleres de habilidades, ferias de empleo",
    carreras: "Administración, Recursos Humanos",
    minAlumnos: 10,
    maxAlumnos: 30,
  },
  {
    id: 7,
    dependencia: "Secretaría de Turismo",
    domicilio: "Av. del Turismo 404",
    telefono: "555-4567",
    nombreTitular: "Luis Gómez",
    cargoTitular: "Director",
    departamento: "Promoción Turística",
    nombreJefe: "Sofía Martínez",
    nombreResponsable: "Carlos López",
    puestoResponsable: "Guía Turístico",
    correoResponsable: "carlos.lopez@turismo.gob",
    nombrePrograma: "Rutas Culturales",
    objetivo: "Promover el turismo cultural",
    actividades: "Visitas guiadas, talleres de artesanía",
    carreras: "Turismo, Historia",
    minAlumnos: 5,
    maxAlumnos: 15,
  },
  {
    id: 8,
    dependencia: "Secretaría de Justicia",
    domicilio: "Calle de la Justicia 505",
    telefono: "555-2345",
    nombreTitular: "Elena Torres",
    cargoTitular: "Fiscal",
    departamento: "Derechos Humanos",
    nombreJefe: "Javier Sánchez",
    nombreResponsable: "Patricia Ruiz",
    puestoResponsable: "Abogada",
    correoResponsable: "patricia.ruiz@justicia.gob",
    nombrePrograma: "Defensa de Derechos Humanos",
    objetivo: "Proteger los derechos de la ciudadanía",
    actividades: "Charlas informativas, asesorías legales",
    carreras: "Derecho, Ciencias Políticas",
    minAlumnos: 8,
    maxAlumnos: 20,
  },
  {
    id: 9,
    dependencia: "Secretaría de Ciencia y Tecnología",
    domicilio: "Calle de la Innovación 606",
    telefono: "555-6789",
    nombreTitular: "Roberto Pérez",
    cargoTitular: "Director",
    departamento: "Investigación",
    nombreJefe: "Laura Gómez",
    nombreResponsable: "Fernando Torres",
    puestoResponsable: "Investigador",
    correoResponsable: "fernando.torres@ciencia.gob",
    nombrePrograma: "Fomento a la Investigación",
    objetivo: "Impulsar proyectos de investigación",
    actividades: "Seminarios, financiamiento de proyectos",
    carreras: "Ciencias, Ingeniería",
    minAlumnos: 10,
    maxAlumnos: 25,
  },
  {
    id: 10,
    dependencia: "Secretaría de Vivienda",
    domicilio: "Calle de la Vivienda 707",
    telefono: "555-3456",
    nombreTitular: "Ana Sánchez",
    cargoTitular: "Directora",
    departamento: "Desarrollo Urbano",
    nombreJefe: "Carlos Martínez",
    nombreResponsable: "Sofía López",
    puestoResponsable: "Arquitecta",
    correoResponsable: "sofia.lopez@vivienda.gob",
    nombrePrograma: "Mejoramiento de Vivienda",
    objetivo: "Mejorar las condiciones de vivienda",
    actividades: "Talleres de construcción, asesorías",
    carreras: "Arquitectura, Urbanismo",
    minAlumnos: 6,
    maxAlumnos: 18,
  },
  {
    id: 11,
    dependencia: "Secretaría de Agricultura",
    domicilio: "Calle del Campo 808",
    telefono: "555-9870",
    nombreTitular: "Pedro Ramírez",
    cargoTitular: "Director",
    departamento: "Desarrollo Agrícola",
    nombreJefe: "Elena Torres",
    nombreResponsable: "Carlos Fernández",
    puestoResponsable: "Agrónomo",
    correoResponsable: "carlos.fernandez@agricultura.gob",
    nombrePrograma: "Capacitación Agrícola",
    objetivo: "Mejorar técnicas de cultivo",
    actividades: "Talleres de agricultura, ferias agrícolas",
    carreras: "Agronomía, Biología",
    minAlumnos: 10,
    maxAlumnos: 30,
  },
  {
    id: 12,
    dependencia: "Secretaría de Transporte",
    domicilio: "Calle del Transporte 909",
    telefono: "555-6540",
    nombreTitular: "María López",
    cargoTitular: "Directora",
    departamento: "Transporte Público",
    nombreJefe: "Roberto Sánchez",
    nombreResponsable: "Ana García",
    puestoResponsable: "Coordinadora",
    correoResponsable: "ana.garcia@transporte.gob",
    nombrePrograma: "Mejoramiento del Transporte Público",
    objetivo: "Optimizar el servicio de transporte",
    actividades: "Estudios de movilidad, talleres de capacitación",
    carreras: "Ingeniería de Transporte, Urbanismo",
    minAlumnos: 8,
    maxAlumnos: 25,
  },
  {
    id: 13,
    dependencia: "Secretaría de Energía",
    domicilio: "Calle de la Energía 1010",
    telefono: "555-3211",
    nombreTitular: "Luis Torres",
    cargoTitular: "Director",
    departamento: "Energías Renovables",
    nombreJefe: "Sofía Martínez",
    nombreResponsable: "Fernando López",
    puestoResponsable: "Ingeniero",
    correoResponsable: "fernando.lopez@energia.gob",
    nombrePrograma: "Fomento a Energías Renovables",
    objetivo: "Promover el uso de energías limpias",
    actividades: "Talleres, proyectos de energía solar",
    carreras: "Ingeniería Ambiental, Energías Renovables",
    minAlumnos: 10,
    maxAlumnos: 30,
  },
  {
    id: 14,
    dependencia: "Secretaría de Comunicación",
    domicilio: "Calle de la Comunicación 1111",
    telefono: "555-4321",
    nombreTitular: "Patricia Ramírez",
    cargoTitular: "Directora",
    departamento: "Relaciones Públicas",
    nombreJefe: "Carlos Pérez",
    nombreResponsable: "Ana Torres",
    puestoResponsable: "Comunicadora",
    correoResponsable: "ana.torres@comunicacion.gob",
    nombrePrograma: "Programa de Comunicación Efectiva",
    objetivo: "Mejorar la comunicación institucional",
    actividades: "Talleres de comunicación, campañas informativas",
    carreras: "Comunicación, Marketing",
    minAlumnos: 5,
    maxAlumnos: 20,
  },
  {
    id: 15,
    dependencia: "Secretaría de Innovación",
    domicilio: "Calle de la Innovación 1212",
    telefono: "555-5671",
    nombreTitular: "Roberto Gómez",
    cargoTitular: "Director",
    departamento: "Desarrollo Tecnológico",
    nombreJefe: "Elena Torres",
    nombreResponsable: "Carlos Ramírez",
    puestoResponsable: "Desarrollador",
    correoResponsable: "carlos.ramirez@innovacion.gob",
    nombrePrograma: "Impulso a la Innovación",
    objetivo: "Fomentar proyectos innovadores",
    actividades: "Hackatones, talleres de tecnología",
    carreras: "Ingeniería en Sistemas, Diseño de Software",
    minAlumnos: 10,
    maxAlumnos: 30,
  },
];
